/**
 * Cascade execution command group metadata.
 *
 * This group contains commands for executing cascade release schedules.
 * Unlike the project-specific cascade commands (which generate schedules),
 * these commands operate at the workspace level to execute schedules.
 *
 * ## Overview
 *
 * The cascade execution commands work with schedules generated by
 * `ftm projects @pkg cascade schedule`:
 *
 * - **run** - Execute a cascade schedule layer by layer
 *
 * ## Workflow
 *
 * ```bash
 * # 1. Generate schedule
 * ftm projects @fathym/dfs cascade schedule --json > schedule.json
 *
 * # 2. Review the schedule (optional)
 * cat schedule.json
 *
 * # 3. Execute the schedule
 * ftm projects cascade run --schedule-file=schedule.json
 *
 * # Or pipe directly
 * ftm projects @fathym/dfs cascade schedule --json | ftm projects cascade run
 * ```
 *
 * @module
 */

import { Group } from '@fathym/cli';

export default Group('cascade')
  .Description('Commands for executing cascade release schedules');
