/**
 * Run command - execute a cascade release schedule.
 *
 * The projects:cascade:run command executes a cascade schedule generated by
 * `ftm projects @pkg cascade schedule`. It processes layers in order, with
 * packages within each layer executed in parallel.
 *
 * ## Usage
 *
 * ```bash
 * # Execute from piped schedule
 * ftm projects @fathym/dfs cascade schedule --json | ftm projects cascade run
 *
 * # Execute from file
 * ftm projects cascade run --schedule-file=./cascade-plan.json
 *
 * # Dry-run to preview what would happen
 * ftm projects cascade run --dry-run --schedule-file=./cascade-plan.json
 *
 * # Continue execution even if a package fails
 * ftm projects cascade run --continue-on-error --schedule-file=./cascade-plan.json
 * ```
 *
 * ## Input Sources
 *
 * The command accepts schedule input from:
 * - **--schedule-file:** Path to a JSON schedule file
 * - **stdin:** Piped JSON from the schedule command
 *
 * If neither is provided, the command waits for stdin input.
 *
 * ## Execution Flow
 *
 * 1. **Validation:** Verifies schedule structure before execution
 * 2. **Layer Processing:** Executes layers in order (0, 1, 2, ...)
 * 3. **Parallel Execution:** Packages in each layer run concurrently
 * 4. **Progress Reporting:** Real-time status updates during execution
 * 5. **Result Summary:** Final report of success/failure counts
 *
 * ## Output
 *
 * The command displays:
 * - Layer-by-layer progress with package names
 * - Success/failure status for each package
 * - Execution duration per layer and total
 * - Final summary with counts
 *
 * In JSON mode (--json), outputs a structured result object.
 *
 * ## Error Handling
 *
 * - **Invalid JSON:** Error with parsing details
 * - **Missing file:** Error if schedule file not found
 * - **Invalid structure:** Error if schedule lacks required fields
 * - **Package failure:** By default stops execution; use --continue-on-error to proceed
 *
 * @example Execute piped schedule
 * ```bash
 * ftm projects @fathym/dfs cascade schedule --json | ftm projects cascade run
 * ```
 *
 * @example Dry-run from file
 * ```bash
 * ftm projects cascade run --dry-run --schedule-file=schedule.json
 * ```
 *
 * @example Continue on errors
 * ```bash
 * ftm projects cascade run --continue-on-error --schedule-file=schedule.json
 * ```
 *
 * @module
 */

import { z } from 'zod';
import { Command, CommandParams, type CommandStatus } from '@fathym/cli';
import {
  type CascadeExecutionResult,
  CascadeExecutor,
  parseSchedule,
} from '../../../src/pipelines/CascadeExecutor.ts';
import type {
  CascadeLayer,
  CascadeLayerPackage,
} from '../../../src/pipelines/CascadeScheduleTypes.ts';

/**
 * Zod schema for run command flags.
 */
const RunFlagsSchema = z.object({
  'schedule-file': z.string().optional().describe(
    'Path to schedule JSON file (alternative to piping)',
  ),
  'dry-run': z.boolean().optional().describe(
    'Preview execution without making changes',
  ),
  'continue-on-error': z.boolean().optional().describe(
    'Continue execution even if a package fails',
  ),
  json: z.boolean().optional().describe(
    'Output as JSON for programmatic consumption',
  ),
  message: z.string().optional().describe(
    'Commit message template ({pkg} for package name)',
  ),
});

/**
 * Zod schema for run command positional arguments.
 */
const RunArgsSchema = z.tuple([]);

/**
 * Typed parameter accessor for the run command.
 */
class RunCommandParams extends CommandParams<
  z.infer<typeof RunArgsSchema>,
  z.infer<typeof RunFlagsSchema>
> {
  /** Path to schedule file */
  get ScheduleFile(): string | undefined {
    return this.Flag('schedule-file');
  }

  /** Whether to run in dry-run mode */
  override get DryRun(): boolean {
    return this.Flag('dry-run') ?? false;
  }

  /** Whether to continue on package failure */
  get ContinueOnError(): boolean {
    return this.Flag('continue-on-error') ?? false;
  }

  /** Whether to output as JSON */
  get Json(): boolean {
    return this.Flag('json') ?? false;
  }

  /** Commit message template */
  get MessageTemplate(): string | undefined {
    return this.Flag('message');
  }
}

/**
 * Read schedule from stdin (for piped input).
 */
async function readStdin(): Promise<string> {
  const decoder = new TextDecoder();
  const chunks: Uint8Array[] = [];

  for await (const chunk of Deno.stdin.readable) {
    chunks.push(chunk);
  }

  return decoder.decode(
    chunks.reduce((acc, chunk) => {
      const newArr = new Uint8Array(acc.length + chunk.length);
      newArr.set(acc);
      newArr.set(chunk, acc.length);
      return newArr;
    }, new Uint8Array()),
  );
}

/**
 * Format execution duration for display.
 */
function formatDuration(ms: number): string {
  if (ms < 1000) {
    return `${ms}ms`;
  }
  const seconds = (ms / 1000).toFixed(1);
  return `${seconds}s`;
}

export default Command(
  'projects:cascade:run',
  'Execute a cascade release schedule.',
)
  .Args(RunArgsSchema)
  .Flags(RunFlagsSchema)
  .Params(RunCommandParams)
  .Run(async ({ Params, Log }): Promise<CommandStatus<CascadeExecutionResult | null>> => {
    const emptyResult: CascadeExecutionResult | null = null;

    try {
      // Get schedule input
      let scheduleInput: string;

      if (Params.ScheduleFile) {
        // Read from file
        scheduleInput = Params.ScheduleFile;
      } else {
        // Read from stdin
        Log.Info('Reading schedule from stdin...');
        scheduleInput = await readStdin();

        if (!scheduleInput.trim()) {
          Log.Error('No schedule provided. Use --schedule-file or pipe from schedule command.');
          return {
            Code: 1,
            Message: 'No schedule provided',
            Data: emptyResult,
          };
        }
      }

      // Parse the schedule
      const schedule = await parseSchedule(scheduleInput);

      // Create executor with progress callbacks
      const callbacks = Params.Json ? {} : {
        onLayerStart: (layer: CascadeLayer) => {
          const packageCount = layer.packages.length;
          const parallelNote = packageCount > 1 ? ` (${packageCount} parallel)` : '';
          const modeNote = Params.DryRun ? ' [DRY RUN]' : '';
          Log.Info(`\nLayer ${layer.index}${parallelNote}${modeNote}`);
        },
        onPackageStart: (pkg: CascadeLayerPackage, _layerIndex: number) => {
          Log.Info(`  → ${pkg.name}...`);
        },
        onPackageComplete: (
          result: { name: string; success: boolean; duration: number; error?: string },
          _layerIndex: number,
        ) => {
          const status = result.success ? '✓' : '✗';
          const duration = formatDuration(result.duration);
          if (result.success) {
            Log.Info(`  ${status} ${result.name} (${duration})`);
          } else {
            Log.Error(
              `  ${status} ${result.name} (${duration}): ${result.error || 'unknown error'}`,
            );
          }
        },
      };

      const executor = new CascadeExecutor(callbacks);

      // Execute the schedule
      if (!Params.Json) {
        const modeLabel = Params.DryRun ? ' (DRY RUN)' : '';
        Log.Info(`### Cascade Execution${modeLabel}`);
        Log.Info(`Root: ${schedule.root}`);
        Log.Info(`Channel: ${schedule.channel}`);
        Log.Info(`Layers: ${schedule.layers.length}`);
        Log.Info(`Packages: ${schedule.totalPackages}`);
      }

      const result = await executor.execute(schedule, {
        dryRun: Params.DryRun,
        continueOnError: Params.ContinueOnError,
        commitMessageTemplate: Params.MessageTemplate,
      });

      // Output results
      if (Params.Json) {
        console.log(JSON.stringify(result, null, 2));
      } else {
        Log.Info('');
        Log.Info('### Summary');
        Log.Info(`Total: ${result.totalPackages} package(s)`);
        Log.Info(`Success: ${result.successCount}`);
        Log.Info(`Failed: ${result.failedCount}`);
        Log.Info(`Duration: ${formatDuration(result.totalDuration)}`);

        if (result.dryRun) {
          Log.Info('');
          Log.Info('(Dry-run mode - no changes were made)');
        }

        if (result.success) {
          Log.Success('\n✅ Cascade execution complete');
        } else {
          Log.Error('\n❌ Cascade execution failed');
        }
      }

      return {
        Code: result.success ? 0 : 1,
        Message: result.success
          ? `Cascade complete: ${result.successCount} packages`
          : `Cascade failed: ${result.failedCount} failures`,
        Data: result,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);

      if (message.includes('Invalid schedule')) {
        Log.Error(`Schedule validation failed: ${message}`);
      } else if (message.includes('not found')) {
        Log.Error(`File not found: ${message}`);
      } else if (message.includes('Invalid JSON')) {
        Log.Error(`Invalid JSON: ${message}`);
      } else {
        Log.Error(`Execution failed: ${message}`);
      }

      return {
        Code: 1,
        Message: message,
        Data: emptyResult,
      };
    }
  });
