/**
 * CascadeExecutor - Layer-by-layer execution engine for cascade schedules.
 *
 * The CascadeExecutor takes a cascade schedule (generated by CascadeScheduler)
 * and executes it layer by layer. Packages within a layer are executed in
 * parallel when possible, as they have no interdependencies.
 *
 * ## Architecture
 *
 * The executor follows the holonic Engine pattern:
 * - **S-A (Self-Assertion):** Internal execution lifecycle, layer processing
 * - **INT (Integration):** Provided by the run command, delegates here
 *
 * ## Execution Flow
 *
 * 1. Validate schedule structure
 * 2. For each layer (in order):
 *    a. Execute all packages in the layer (parallel when possible)
 *    b. Wait for all packages to complete
 *    c. Report layer status
 * 3. Return execution results
 *
 * ## Features
 *
 * - **Dry-run mode:** Preview what would be executed without making changes
 * - **Parallel layer execution:** Packages in the same layer run concurrently
 * - **Progress reporting:** Callbacks for real-time status updates
 * - **Error handling:** Configurable behavior on package failure
 *
 * @example Basic usage
 * ```typescript
 * const executor = new CascadeExecutor({
 *   onLayerStart: (layer) => console.log(`Starting layer ${layer.index}`),
 *   onPackageComplete: (pkg) => console.log(`${pkg.name} complete`),
 * });
 *
 * const result = await executor.execute(schedule);
 * ```
 *
 * @example Dry-run mode
 * ```typescript
 * const result = await executor.execute(schedule, { dryRun: true });
 * // Logs what would happen without executing
 * ```
 *
 * @module
 */

import type { CascadeLayer, CascadeLayerPackage, CascadeSchedule } from './CascadeScheduleTypes.ts';

/**
 * Result of executing a single package.
 */
export interface PackageExecutionResult {
  /** Package name */
  name: string;
  /** Whether execution succeeded */
  success: boolean;
  /** Error message if failed */
  error?: string;
  /** Duration in milliseconds */
  duration: number;
  /** Whether this was a dry-run */
  dryRun: boolean;
}

/**
 * Result of executing a single layer.
 */
export interface LayerExecutionResult {
  /** Layer index */
  index: number;
  /** Results for each package in the layer */
  packages: PackageExecutionResult[];
  /** Total layer duration in milliseconds */
  duration: number;
  /** Whether all packages succeeded */
  allSucceeded: boolean;
}

/**
 * Complete result of executing a cascade schedule.
 */
export interface CascadeExecutionResult {
  /** Root package names (all roots from Layer 0) */
  roots: string[];
  /** First root package name (backward compatibility) */
  root: string;
  /** Release channel */
  channel: string;
  /** Results for each layer */
  layers: LayerExecutionResult[];
  /** Total execution duration in milliseconds */
  totalDuration: number;
  /** Total packages executed */
  totalPackages: number;
  /** Number of successful packages */
  successCount: number;
  /** Number of failed packages */
  failedCount: number;
  /** Whether this was a dry-run */
  dryRun: boolean;
  /** Overall success (all packages succeeded) */
  success: boolean;
}

/**
 * Options for cascade execution.
 */
export interface CascadeExecutionOptions {
  /**
   * Dry-run mode - preview execution without making changes.
   * Default: false
   */
  dryRun?: boolean;

  /**
   * Continue execution even if a package fails.
   * If false, stops at the first failure.
   * Default: false
   */
  continueOnError?: boolean;

  /**
   * Commit message template for package releases.
   * Use {pkg} as placeholder for package name.
   * Default: "chore({pkg}): cascade release"
   */
  commitMessageTemplate?: string;
}

/**
 * Callbacks for execution progress reporting.
 */
export interface CascadeExecutionCallbacks {
  /**
   * Called when a layer starts execution.
   */
  onLayerStart?: (layer: CascadeLayer) => void;

  /**
   * Called when a layer completes execution.
   */
  onLayerComplete?: (result: LayerExecutionResult) => void;

  /**
   * Called when a package starts execution.
   */
  onPackageStart?: (pkg: CascadeLayerPackage, layerIndex: number) => void;

  /**
   * Called when a package completes execution.
   */
  onPackageComplete?: (
    result: PackageExecutionResult,
    layerIndex: number,
  ) => void;
}

/**
 * Function type for executing a single package.
 * This is injected to allow testing and different execution strategies.
 */
export type PackageExecutor = (
  pkg: CascadeLayerPackage,
  options: CascadeExecutionOptions,
) => Promise<PackageExecutionResult>;

/**
 * Default package executor - placeholder that simulates execution.
 * In production, this would be replaced with actual build/commit/push logic.
 */
async function defaultPackageExecutor(
  pkg: CascadeLayerPackage,
  options: CascadeExecutionOptions,
): Promise<PackageExecutionResult> {
  const startTime = Date.now();

  if (options.dryRun) {
    // Simulate a short delay for dry-run
    await new Promise((resolve) => setTimeout(resolve, 10));
    return {
      name: pkg.name,
      success: true,
      duration: Date.now() - startTime,
      dryRun: true,
    };
  }

  // Actual execution would go here - build, commit, push, poll for CI
  // For now, return a simulated result
  await new Promise((resolve) => setTimeout(resolve, 50));
  return {
    name: pkg.name,
    success: true,
    duration: Date.now() - startTime,
    dryRun: false,
  };
}

/**
 * CascadeExecutor - executes cascade schedules layer by layer.
 *
 * This class provides the execution engine for cascade releases. It takes
 * a schedule generated by CascadeScheduler and executes each layer in order,
 * with packages within a layer running in parallel.
 *
 * ## Usage
 *
 * ```typescript
 * const executor = new CascadeExecutor({
 *   onLayerStart: (layer) => console.log(`Layer ${layer.index}`),
 * });
 *
 * const result = await executor.execute(schedule, { dryRun: true });
 * ```
 */
export class CascadeExecutor {
  private readonly callbacks: CascadeExecutionCallbacks;
  private readonly packageExecutor: PackageExecutor;

  /**
   * Create a new CascadeExecutor.
   *
   * @param callbacks - Optional callbacks for progress reporting
   * @param packageExecutor - Optional custom package executor for testing
   */
  constructor(
    callbacks: CascadeExecutionCallbacks = {},
    packageExecutor: PackageExecutor = defaultPackageExecutor,
  ) {
    this.callbacks = callbacks;
    this.packageExecutor = packageExecutor;
  }

  /**
   * Execute a cascade schedule.
   *
   * Processes the schedule layer by layer, executing packages within each
   * layer in parallel. Returns a complete execution result.
   *
   * @param schedule - The cascade schedule to execute
   * @param options - Execution options (dryRun, continueOnError, etc.)
   * @returns Complete execution result
   * @throws Error if schedule is invalid
   */
  async execute(
    schedule: CascadeSchedule,
    options: CascadeExecutionOptions = {},
  ): Promise<CascadeExecutionResult> {
    // Validate schedule
    this.validateSchedule(schedule);

    const startTime = Date.now();
    const layerResults: LayerExecutionResult[] = [];
    let successCount = 0;
    let failedCount = 0;
    let shouldStop = false;

    // Execute each layer in order
    for (const layer of schedule.layers) {
      if (shouldStop) break;

      // Notify layer start
      this.callbacks.onLayerStart?.(layer);

      // Execute layer
      const layerResult = await this.executeLayer(layer, options);
      layerResults.push(layerResult);

      // Notify layer complete
      this.callbacks.onLayerComplete?.(layerResult);

      // Update counts
      for (const pkgResult of layerResult.packages) {
        if (pkgResult.success) {
          successCount++;
        } else {
          failedCount++;
        }
      }

      // Check if we should stop on error
      if (!layerResult.allSucceeded && !options.continueOnError) {
        shouldStop = true;
      }
    }

    const totalDuration = Date.now() - startTime;

    // Handle both roots array and legacy root field
    const roots = schedule.roots ?? [schedule.root];

    return {
      roots,
      root: roots[0],
      channel: schedule.channel,
      layers: layerResults,
      totalDuration,
      totalPackages: successCount + failedCount,
      successCount,
      failedCount,
      dryRun: options.dryRun ?? false,
      success: failedCount === 0,
    };
  }

  /**
   * Execute a single layer, running all packages in parallel.
   *
   * @param layer - The layer to execute
   * @param options - Execution options
   * @returns Layer execution result
   */
  private async executeLayer(
    layer: CascadeLayer,
    options: CascadeExecutionOptions,
  ): Promise<LayerExecutionResult> {
    const startTime = Date.now();

    // Execute all packages in parallel
    const packagePromises = layer.packages.map(async (pkg) => {
      // Notify package start
      this.callbacks.onPackageStart?.(pkg, layer.index);

      // Execute package
      const result = await this.packageExecutor(pkg, options);

      // Notify package complete
      this.callbacks.onPackageComplete?.(result, layer.index);

      return result;
    });

    const packageResults = await Promise.all(packagePromises);
    const duration = Date.now() - startTime;
    const allSucceeded = packageResults.every((r) => r.success);

    return {
      index: layer.index,
      packages: packageResults,
      duration,
      allSucceeded,
    };
  }

  /**
   * Validate a cascade schedule structure.
   *
   * @param schedule - The schedule to validate
   * @throws Error if schedule is invalid
   */
  private validateSchedule(schedule: CascadeSchedule): void {
    // Accept either roots array or legacy root field
    const hasRoot = schedule.root ||
      (schedule.roots && schedule.roots.length > 0);
    if (!hasRoot) {
      throw new Error('Invalid schedule: missing root package(s)');
    }

    if (!schedule.channel) {
      throw new Error('Invalid schedule: missing channel');
    }

    if (!Array.isArray(schedule.layers)) {
      throw new Error('Invalid schedule: layers must be an array');
    }

    if (schedule.layers.length === 0) {
      throw new Error('Invalid schedule: no layers to execute');
    }

    // Validate each layer
    for (const layer of schedule.layers) {
      if (typeof layer.index !== 'number') {
        throw new Error(`Invalid schedule: layer missing index`);
      }

      if (!Array.isArray(layer.packages)) {
        throw new Error(
          `Invalid schedule: layer ${layer.index} packages must be an array`,
        );
      }

      if (layer.packages.length === 0) {
        throw new Error(
          `Invalid schedule: layer ${layer.index} has no packages`,
        );
      }

      // Validate each package
      for (const pkg of layer.packages) {
        if (!pkg.name) {
          throw new Error(
            `Invalid schedule: package in layer ${layer.index} missing name`,
          );
        }
      }
    }
  }
}

/**
 * Parse a cascade schedule from JSON.
 *
 * Reads a JSON file or string and parses it into a CascadeSchedule.
 * Validates the structure before returning.
 *
 * @param input - JSON string or file path
 * @returns Parsed schedule
 * @throws Error if JSON is invalid or schedule structure is invalid
 */
export async function parseSchedule(input: string): Promise<CascadeSchedule> {
  let schedule: CascadeSchedule;

  // Check if input is a file path
  if (input.endsWith('.json')) {
    try {
      const content = await Deno.readTextFile(input);
      schedule = JSON.parse(content);
    } catch (error) {
      if (error instanceof Deno.errors.NotFound) {
        throw new Error(`Schedule file not found: ${input}`);
      }
      throw new Error(
        `Failed to read schedule file: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  } else {
    // Parse as JSON string
    try {
      schedule = JSON.parse(input);
    } catch {
      throw new Error('Invalid JSON: failed to parse schedule');
    }
  }

  // Basic structure validation
  if (!schedule || typeof schedule !== 'object') {
    throw new Error('Invalid schedule: must be an object');
  }

  return schedule;
}
