/**
 * Install Scripts command - generates platform-specific installation scripts.
 *
 * The install-scripts command creates shell scripts that users can download
 * and run to install the CLI binary. These scripts are intended for users
 * who don't have Deno installed and want a simple installation experience.
 *
 * ## Generated Scripts
 *
 * - `install.sh` - Bash script for macOS and Linux
 * - `install.ps1` - PowerShell script for Windows
 *
 * ## Script Features
 *
 * Both scripts:
 * - Auto-detect OS and architecture
 * - Download the appropriate binary from GitHub Releases
 * - Install to a configurable directory (default: ~/.bin)
 * - Create alias scripts for additional tokens
 * - Output PATH configuration instructions
 *
 * ## Output Location
 *
 * Scripts are generated to `.dist/` alongside the compiled binaries:
 *
 * ```
 * .dist/
 * ├── install.sh
 * ├── install.ps1
 * ├── x86_64-pc-windows-msvc/
 * │   └── my-cli.exe
 * └── x86_64-apple-darwin/
 *     └── my-cli
 * ```
 *
 * @example Generate install scripts
 * ```bash
 * ftm cli install-scripts
 * ```
 *
 * @example Generate with custom GitHub repo
 * ```bash
 * ftm cli install-scripts --repo=myorg/my-cli
 * ```
 *
 * @example Generate with custom install directory
 * ```bash
 * ftm cli install-scripts --installDir=~/.local/bin
 * ```
 *
 * @module
 */

import { join } from '@std/path';
import { z } from 'zod';
import { CLIDFSContextManager, Command, CommandParams, loadCLIConfig } from '@fathym/cli';
import {
  DEFAULT_INSTALL_DIR,
  DEFAULT_TARGETS,
  type FathymCLIConfig,
} from '../../src/FathymCLIConfig.ts';

/**
 * Zod schema for install-scripts command positional arguments.
 */
export const InstallScriptsArgsSchema = z.tuple([]);

/**
 * Zod schema for install-scripts command flags.
 *
 * @property config - Path to .cli.json configuration
 * @property repo - GitHub repository (owner/repo format)
 * @property output - Output directory for scripts
 * @property installDir - Default install directory in generated scripts
 */
export const InstallScriptsFlagsSchema = z
  .object({
    config: z
      .string()
      .optional()
      .describe('Path to .cli.json (default: ./.cli.json)'),
    repo: z
      .string()
      .optional()
      .describe('GitHub repository (owner/repo). Auto-detected from .git/config if not specified'),
    output: z
      .string()
      .optional()
      .describe('Output directory for scripts (default: ./.dist)'),
    installDir: z
      .string()
      .optional()
      .describe('Default install directory in scripts (default: ~/.bin)'),
  })
  .passthrough();

/**
 * Typed parameter accessor for the install-scripts command.
 */
export class InstallScriptsParams extends CommandParams<
  z.infer<typeof InstallScriptsArgsSchema>,
  z.infer<typeof InstallScriptsFlagsSchema>
> {
  get ConfigPath(): string | undefined {
    return this.Flag('config');
  }

  get Repo(): string | undefined {
    return this.Flag('repo');
  }

  get OutputDir(): string {
    return this.Flag('output') ?? './.dist';
  }

  get InstallDir(): string {
    return this.Flag('installDir') ?? DEFAULT_INSTALL_DIR.unix;
  }
}

/**
 * Attempts to detect the GitHub repository from .git/config.
 */
async function detectGitHubRepo(cwd: string): Promise<string | undefined> {
  try {
    const gitConfigPath = join(cwd, '.git', 'config');
    const content = await Deno.readTextFile(gitConfigPath);

    // Match GitHub remote URL patterns
    const httpsMatch = content.match(/url\s*=\s*https:\/\/github\.com\/([^/]+\/[^/\s]+?)(?:\.git)?$/m);
    const sshMatch = content.match(/url\s*=\s*git@github\.com:([^/]+\/[^/\s]+?)(?:\.git)?$/m);

    const match = httpsMatch || sshMatch;
    return match ? match[1].replace(/\.git$/, '') : undefined;
  } catch {
    return undefined;
  }
}

/**
 * Generates the bash install script for macOS and Linux.
 */
function generateBashScript(
  binaryName: string,
  repo: string,
  installDir: string,
  aliases: string[],
): string {
  return `#!/bin/bash
# Install script for ${binaryName}
# Generated by Fathym CLI

set -e

REPO="${repo}"
BINARY_NAME="${binaryName}"
INSTALL_DIR="\${INSTALL_DIR:-${installDir}}"

# Detect OS and architecture
detect_target() {
  local os arch
  os="$(uname -s)"
  arch="$(uname -m)"

  case "$os" in
    Darwin)
      case "$arch" in
        x86_64) echo "x86_64-apple-darwin" ;;
        arm64)  echo "aarch64-apple-darwin" ;;
        *)      echo "Unsupported architecture: $arch" >&2; exit 1 ;;
      esac
      ;;
    Linux)
      case "$arch" in
        x86_64)  echo "x86_64-unknown-linux-gnu" ;;
        aarch64) echo "aarch64-unknown-linux-gnu" ;;
        *)       echo "Unsupported architecture: $arch" >&2; exit 1 ;;
      esac
      ;;
    *)
      echo "Unsupported OS: $os" >&2
      exit 1
      ;;
  esac
}

# Get the latest release tag
get_latest_version() {
  curl -sL "https://api.github.com/repos/$REPO/releases/latest" | \\
    grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\\1/'
}

main() {
  echo "🔍 Detecting platform..."
  TARGET="$(detect_target)"
  echo "   Target: $TARGET"

  echo "📦 Fetching latest version..."
  VERSION="\${VERSION:-$(get_latest_version)}"
  echo "   Version: $VERSION"

  # Expand ~ in INSTALL_DIR
  INSTALL_DIR="\${INSTALL_DIR/#\\~/$HOME}"

  echo "📁 Creating install directory: $INSTALL_DIR"
  mkdir -p "$INSTALL_DIR"

  DOWNLOAD_URL="https://github.com/$REPO/releases/download/$VERSION/$TARGET-$BINARY_NAME"
  BINARY_PATH="$INSTALL_DIR/$BINARY_NAME"

  echo "⬇️  Downloading $BINARY_NAME..."
  curl -sL "$DOWNLOAD_URL" -o "$BINARY_PATH"
  chmod +x "$BINARY_PATH"
  echo "✅ Installed: $BINARY_PATH"

  # Create aliases
${aliases.map((alias) => `  echo '#!/bin/sh
exec "$BINARY_NAME" "$@"' > "$INSTALL_DIR/${alias}"
  chmod +x "$INSTALL_DIR/${alias}"
  echo "🔗 Alias created: $INSTALL_DIR/${alias}"`).join('\n')}

  # Check if in PATH
  if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
    echo ""
    echo "⚠️  $INSTALL_DIR is not in your PATH"
    echo "👉 Add this to your shell profile (~/.bashrc, ~/.zshrc, etc.):"
    echo ""
    echo "   export PATH=\\"$INSTALL_DIR:\\$PATH\\""
    echo ""
  fi

  echo ""
  echo "🎉 Installation complete!"
  echo "   Run '$BINARY_NAME --help' to get started."
}

main "$@"
`;
}

/**
 * Generates the PowerShell install script for Windows.
 */
function generatePowerShellScript(
  binaryName: string,
  repo: string,
  installDir: string,
  aliases: string[],
): string {
  return `# Install script for ${binaryName}
# Generated by Fathym CLI

$ErrorActionPreference = "Stop"

$Repo = "${repo}"
$BinaryName = "${binaryName}"
$InstallDir = if ($env:INSTALL_DIR) { $env:INSTALL_DIR } else { "${installDir}" }
$Target = "x86_64-pc-windows-msvc"

function Get-LatestVersion {
    $response = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repo/releases/latest"
    return $response.tag_name
}

function Main {
    Write-Host "📦 Fetching latest version..." -ForegroundColor Cyan
    $Version = if ($env:VERSION) { $env:VERSION } else { Get-LatestVersion }
    Write-Host "   Version: $Version"

    # Expand ~ in InstallDir
    $InstallDir = $InstallDir -replace "^~", $env:USERPROFILE

    Write-Host "📁 Creating install directory: $InstallDir" -ForegroundColor Cyan
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

    $DownloadUrl = "https://github.com/$Repo/releases/download/$Version/$Target-$BinaryName.exe"
    $BinaryPath = Join-Path $InstallDir "$BinaryName.exe"

    Write-Host "⬇️  Downloading $BinaryName..." -ForegroundColor Cyan
    Invoke-WebRequest -Uri $DownloadUrl -OutFile $BinaryPath
    Write-Host "✅ Installed: $BinaryPath" -ForegroundColor Green

    # Create aliases
${aliases.map((alias) => `    $AliasPath = Join-Path $InstallDir "${alias}.cmd"
    "@echo off\`r\`n$BinaryName.exe %*" | Out-File -FilePath $AliasPath -Encoding ASCII
    Write-Host "🔗 Alias created: $AliasPath" -ForegroundColor Cyan`).join('\n')}

    # Check if in PATH
    $PathDirs = $env:PATH -split ";"
    if ($PathDirs -notcontains $InstallDir) {
        Write-Host ""
        Write-Host "⚠️  $InstallDir is not in your PATH" -ForegroundColor Yellow
        Write-Host "👉 Add it to your PATH with:" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "   setx PATH \\"%PATH%;$InstallDir\\"" -ForegroundColor White
        Write-Host ""
    }

    Write-Host ""
    Write-Host "🎉 Installation complete!" -ForegroundColor Green
    Write-Host "   Run '$BinaryName --help' to get started."
}

Main
`;
}

/**
 * Install Scripts command - generates platform-specific installation scripts.
 */
export default Command(
  'install-scripts',
  'Generate install.sh and install.ps1 scripts',
)
  .Args(InstallScriptsArgsSchema)
  .Flags(InstallScriptsFlagsSchema)
  .Params(InstallScriptsParams)
  .Services(async (ctx, ioc) => {
    const dfsCtx = await ioc.Resolve(CLIDFSContextManager);

    if (ctx.Params.ConfigPath) {
      await dfsCtx.RegisterProjectDFS(ctx.Params.ConfigPath, 'CLI');
    }

    const dfs = ctx.Params.ConfigPath
      ? await dfsCtx.GetDFS('CLI')
      : await dfsCtx.GetExecutionDFS();

    return { DFS: dfs };
  })
  .Run(async ({ Params, Log, Services }) => {
    const { DFS } = Services;

    // Load config
    const configPath = await DFS.ResolvePath('.cli.json');
    const config = await loadCLIConfig<FathymCLIConfig>(configPath);

    const tokens = config.Tokens ?? ['cli'];
    const binaryName = tokens[0];
    const aliases = tokens.slice(1);

    // Detect or use provided repo
    let repo = Params.Repo;
    if (!repo) {
      repo = await detectGitHubRepo(DFS.Root);
      if (!repo) {
        Log.Error('❌ Could not detect GitHub repository from .git/config');
        Log.Error('   Use --repo=owner/repo to specify manually');
        Deno.exit(1);
      }
      Log.Info(`📦 Detected GitHub repo: ${repo}`);
    }

    const outputDir = await DFS.ResolvePath(Params.OutputDir);
    await Deno.mkdir(outputDir, { recursive: true });

    // Generate bash script
    const bashScript = generateBashScript(binaryName, repo, Params.InstallDir, aliases);
    const bashPath = join(outputDir, 'install.sh');
    await Deno.writeTextFile(bashPath, bashScript);
    Log.Success(`✅ Generated: ${bashPath}`);

    // Generate PowerShell script
    const psScript = generatePowerShellScript(binaryName, repo, Params.InstallDir, aliases);
    const psPath = join(outputDir, 'install.ps1');
    await Deno.writeTextFile(psPath, psScript);
    Log.Success(`✅ Generated: ${psPath}`);

    Log.Info('');
    Log.Info('📋 Users can install via:');
    Log.Info('');
    Log.Info('   # macOS/Linux');
    Log.Info(`   curl -fsSL https://github.com/${repo}/releases/latest/download/install.sh | bash`);
    Log.Info('');
    Log.Info('   # Windows PowerShell');
    Log.Info(`   iwr -useb https://github.com/${repo}/releases/latest/download/install.ps1 | iex`);
  });
